import type { Metadata } from "next";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import Navigation from "../components/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <UserProvider>
        <body>
          <Navigation />
          {children}
        </body>
      </UserProvider>
    </html>
  );
}
