import type { Metadata } from "next";
import { UserProvider } from "@auth0/nextjs-auth0/client";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <UserProvider>
        <body>
          <a href="/api/auth/signup">Signup</a>
          <a href="/api/auth/login">Login</a>
          <a href="/api/auth/logout">Logout</a>
          {children}
        </body>
      </UserProvider>
    </html>
  );
}
